spring:
    application:
        name: clab-docker-demo
    
logging:
    level:
        org.springframework.cloud.kubernetes: DEBUG
        com.bns.docker.clabdockerdemo: DEBUG
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
    
myprefix:
    fixedProp: "Fixed Prop from application.yml"
  
---
spring:
    profiles: default
server:
    port: 8081

myprefix:
    propFromConfigMap: "Prop From Config Map from default profile"
    genClassCount: 1
    memToConsumeMb: 2
    sleepThread: false

---
spring:
    profiles: kubernetes
server:
    port: 8082

myprefix:
    propFromConfigMap: "Prop From Config Map from default profile"
    genClassCount: 1
    memToConsumeMb: 2
    sleepThread: false